# Generated by Django 3.1.4 on 2021-07-20 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ground', '0006_auto_20210717_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='title',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='image',
            name='comments',
            field=models.TextField(blank=True, default=''),
        ),
    ]
