# Generated by Django 3.1.4 on 2021-07-22 09:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ground', '0007_auto_20210720_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profilePic',
        ),
        migrations.AddField(
            model_name='gig',
            name='date_of_expiry',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gig',
            name='departure_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gig',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gig',
            name='return_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_premium_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='image',
            name='comments',
            field=models.TextField(blank=True, default='IMAGE_'),
        ),
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.TextField(default=''),
        ),
    ]
